### List all messages
GET http://localhost:3000/messages

### Create new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Hel-o-o-o-o1112345"
}

### Get a particular message
GET http://localhost:3000/messages/97